# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Popover::LeftComponent`.
# Please instead update this file by running `bin/tapioca dsl Popover::LeftComponent`.

class Popover::LeftComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
