# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Popover::RightComponent`.
# Please instead update this file by running `bin/tapioca dsl Popover::RightComponent`.

class Popover::RightComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
