# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Popover::TopComponent`.
# Please instead update this file by running `bin/tapioca dsl Popover::TopComponent`.

class Popover::TopComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
