# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Badge::BadgeComponent`.
# Please instead update this file by running `bin/tapioca dsl Badge::BadgeComponent`.

class Badge::BadgeComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
