# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Timeline::TimelineComponent`.
# Please instead update this file by running `bin/tapioca dsl Timeline::TimelineComponent`.

class Timeline::TimelineComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
