# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Breadcrumb::BreadcrumbComponent`.
# Please instead update this file by running `bin/tapioca dsl Breadcrumb::BreadcrumbComponent`.

class Breadcrumb::BreadcrumbComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
