# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Box::FlatComponent`.
# Please instead update this file by running `bin/tapioca dsl Box::FlatComponent`.

class Box::FlatComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
