# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Avatar::CircleComponent`.
# Please instead update this file by running `bin/tapioca dsl Avatar::CircleComponent`.

class Avatar::CircleComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
