# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Avatar::SquareComponent`.
# Please instead update this file by running `bin/tapioca dsl Avatar::SquareComponent`.

class Avatar::SquareComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
