# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Button::ButtonComponent`.
# Please instead update this file by running `bin/tapioca dsl Button::ButtonComponent`.

class Button::ButtonComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
