# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Button::ExitComponent`.
# Please instead update this file by running `bin/tapioca dsl Button::ExitComponent`.

class Button::ExitComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
