# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Button::JumbotronComponent`.
# Please instead update this file by running `bin/tapioca dsl Button::JumbotronComponent`.

class Button::JumbotronComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
