# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Button::LinkComponent`.
# Please instead update this file by running `bin/tapioca dsl Button::LinkComponent`.

class Button::LinkComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
