# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Button::ToggleLeftSidebarComponent`.
# Please instead update this file by running `bin/tapioca dsl Button::ToggleLeftSidebarComponent`.

class Button::ToggleLeftSidebarComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
