# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Button::ToggleRightSidebarComponent`.
# Please instead update this file by running `bin/tapioca dsl Button::ToggleRightSidebarComponent`.

class Button::ToggleRightSidebarComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
