# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Sidebar::LeftComponent`.
# Please instead update this file by running `bin/tapioca dsl Sidebar::LeftComponent`.

class Sidebar::LeftComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
