# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Sidebar::RightComponent`.
# Please instead update this file by running `bin/tapioca dsl Sidebar::RightComponent`.

class Sidebar::RightComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
