# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Picker::ColorComponent`.
# Please instead update this file by running `bin/tapioca dsl Picker::ColorComponent`.

class Picker::ColorComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
