# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Picker::DateTimeComponent`.
# Please instead update this file by running `bin/tapioca dsl Picker::DateTimeComponent`.

class Picker::DateTimeComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
