# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Picker::TimeComponent`.
# Please instead update this file by running `bin/tapioca dsl Picker::TimeComponent`.

class Picker::TimeComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
