# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `React::LoveComponent`.
# Please instead update this file by running `bin/tapioca dsl React::LoveComponent`.

class React::LoveComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
