# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `React::RatingComponent`.
# Please instead update this file by running `bin/tapioca dsl React::RatingComponent`.

class React::RatingComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
