# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Banner::BottomComponent`.
# Please instead update this file by running `bin/tapioca dsl Banner::BottomComponent`.

class Banner::BottomComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
