# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Banner::TopComponent`.
# Please instead update this file by running `bin/tapioca dsl Banner::TopComponent`.

class Banner::TopComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
