# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Quote::QuoteComponent`.
# Please instead update this file by running `bin/tapioca dsl Quote::QuoteComponent`.

class Quote::QuoteComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
