# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Toast::ToastComponent`.
# Please instead update this file by running `bin/tapioca dsl Toast::ToastComponent`.

class Toast::ToastComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
