# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Dial::BottomLeftComponent`.
# Please instead update this file by running `bin/tapioca dsl Dial::BottomLeftComponent`.

class Dial::BottomLeftComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
