# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Dial::BottomRightComponent`.
# Please instead update this file by running `bin/tapioca dsl Dial::BottomRightComponent`.

class Dial::BottomRightComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
