# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Dial::DialComponent`.
# Please instead update this file by running `bin/tapioca dsl Dial::DialComponent`.

class Dial::DialComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
