# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Dial::LeftRightComponent`.
# Please instead update this file by running `bin/tapioca dsl Dial::LeftRightComponent`.

class Dial::LeftRightComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
