# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Dial::TopLeftComponent`.
# Please instead update this file by running `bin/tapioca dsl Dial::TopLeftComponent`.

class Dial::TopLeftComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
