# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Dial::TopRightComponent`.
# Please instead update this file by running `bin/tapioca dsl Dial::TopRightComponent`.

class Dial::TopRightComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
