# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mockup::DefaultComponent`.
# Please instead update this file by running `bin/tapioca dsl Mockup::DefaultComponent`.

class Mockup::DefaultComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
