# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mockup::DesktopComponent`.
# Please instead update this file by running `bin/tapioca dsl Mockup::DesktopComponent`.

class Mockup::DesktopComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
