# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mockup::Iphone12Component`.
# Please instead update this file by running `bin/tapioca dsl Mockup::Iphone12Component`.

class Mockup::Iphone12Component
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
