# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mockup::LaptopComponent`.
# Please instead update this file by running `bin/tapioca dsl Mockup::LaptopComponent`.

class Mockup::LaptopComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
