# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Mockup::SmartwatchComponent`.
# Please instead update this file by running `bin/tapioca dsl Mockup::SmartwatchComponent`.

class Mockup::SmartwatchComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
