# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Blockquote::DefaultComponent`.
# Please instead update this file by running `bin/tapioca dsl Blockquote::DefaultComponent`.

class Blockquote::DefaultComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
