# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Blockquote::IconComponent`.
# Please instead update this file by running `bin/tapioca dsl Blockquote::IconComponent`.

class Blockquote::IconComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
