# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Blockquote::ParagraphComponent`.
# Please instead update this file by running `bin/tapioca dsl Blockquote::ParagraphComponent`.

class Blockquote::ParagraphComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
