# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Blockquote::RatingComponent`.
# Please instead update this file by running `bin/tapioca dsl Blockquote::RatingComponent`.

class Blockquote::RatingComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
