# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Blockquote::SolidComponent`.
# Please instead update this file by running `bin/tapioca dsl Blockquote::SolidComponent`.

class Blockquote::SolidComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
