# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Blockquote::TestimonialComponent`.
# Please instead update this file by running `bin/tapioca dsl Blockquote::TestimonialComponent`.

class Blockquote::TestimonialComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
