# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tooltip::TooltipComponent`.
# Please instead update this file by running `bin/tapioca dsl Tooltip::TooltipComponent`.

class Tooltip::TooltipComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
