# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::CheckboxComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::CheckboxComponent`.

class Input::CheckboxComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
