# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::FloatingStandardLabelComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::FloatingStandardLabelComponent`.

class Input::FloatingStandardLabelComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
