# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::FloatingFilledLabelComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::FloatingFilledLabelComponent`.

class Input::FloatingFilledLabelComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
