# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::FloatingOutlinedLabelComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::FloatingOutlinedLabelComponent`.

class Input::FloatingOutlinedLabelComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
