# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::LabelComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::LabelComponent`.

class Input::LabelComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
