# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::RadioComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::RadioComponent`.

class Input::RadioComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
