# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::RangeSliderComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::RangeSliderComponent`.

class Input::RangeSliderComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
