# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::SelectComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::SelectComponent`.

class Input::SelectComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
