# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::ToggleComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::ToggleComponent`.

class Input::ToggleComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
