# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Alert::DangerComponent`.
# Please instead update this file by running `bin/tapioca dsl Alert::DangerComponent`.

class Alert::DangerComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
