# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Alert::DarkComponent`.
# Please instead update this file by running `bin/tapioca dsl Alert::DarkComponent`.

class Alert::DarkComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
