# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Alert::InfoComponent`.
# Please instead update this file by running `bin/tapioca dsl Alert::InfoComponent`.

class Alert::InfoComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
