# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Alert::SuccessComponent`.
# Please instead update this file by running `bin/tapioca dsl Alert::SuccessComponent`.

class Alert::SuccessComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
