# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Alert::WarningComponent`.
# Please instead update this file by running `bin/tapioca dsl Alert::WarningComponent`.

class Alert::WarningComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
