# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Search::SearchComponent`.
# Please instead update this file by running `bin/tapioca dsl Search::SearchComponent`.

class Search::SearchComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
