# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Card::CardComponent`.
# Please instead update this file by running `bin/tapioca dsl Card::CardComponent`.

class Card::CardComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
