# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Main::ArticleComponent`.
# Please instead update this file by running `bin/tapioca dsl Main::ArticleComponent`.

class Main::ArticleComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
