# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Main::MainComponent`.
# Please instead update this file by running `bin/tapioca dsl Main::MainComponent`.

class Main::MainComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
