# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Waiting::SpinnerComponent`.
# Please instead update this file by running `bin/tapioca dsl Waiting::SpinnerComponent`.

class Waiting::SpinnerComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
