# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Dropdown::ClickComponent`.
# Please instead update this file by running `bin/tapioca dsl Dropdown::ClickComponent`.

class Dropdown::ClickComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
