# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Gallery::EqualComponent`.
# Please instead update this file by running `bin/tapioca dsl Gallery::EqualComponent`.

class Gallery::EqualComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
