# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Gallery::FeatureComponent`.
# Please instead update this file by running `bin/tapioca dsl Gallery::FeatureComponent`.

class Gallery::FeatureComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
