# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Gallery::GalleryComponent`.
# Please instead update this file by running `bin/tapioca dsl Gallery::GalleryComponent`.

class Gallery::GalleryComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
