# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Gallery::MasonryComponent`.
# Please instead update this file by running `bin/tapioca dsl Gallery::MasonryComponent`.

class Gallery::MasonryComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
