# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Gallery::QuadComponent`.
# Please instead update this file by running `bin/tapioca dsl Gallery::QuadComponent`.

class Gallery::QuadComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
