# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Gallery::SliderComponent`.
# Please instead update this file by running `bin/tapioca dsl Gallery::SliderComponent`.

class Gallery::SliderComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
