# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Spinner::SpinnerComponent`.
# Please instead update this file by running `bin/tapioca dsl Spinner::SpinnerComponent`.

class Spinner::SpinnerComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
