# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carousel::CarouselComponent`.
# Please instead update this file by running `bin/tapioca dsl Carousel::CarouselComponent`.

class Carousel::CarouselComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
