# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Body::BodyComponent`.
# Please instead update this file by running `bin/tapioca dsl Body::BodyComponent`.

class Body::BodyComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
