# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Body::FooterComponent`.
# Please instead update this file by running `bin/tapioca dsl Body::FooterComponent`.

class Body::FooterComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
