# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Body::HeaderComponent`.
# Please instead update this file by running `bin/tapioca dsl Body::HeaderComponent`.

class Body::HeaderComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
