# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Body::NavComponent`.
# Please instead update this file by running `bin/tapioca dsl Body::NavComponent`.

class Body::NavComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
