# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Table::BodyComponent`.
# Please instead update this file by running `bin/tapioca dsl Table::BodyComponent`.

class Table::BodyComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
