# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Table::HeaderComponent`.
# Please instead update this file by running `bin/tapioca dsl Table::HeaderComponent`.

class Table::HeaderComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
