# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Table::HeadComponent`.
# Please instead update this file by running `bin/tapioca dsl Table::HeadComponent`.

class Table::HeadComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
