# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Table::TableComponent`.
# Please instead update this file by running `bin/tapioca dsl Table::TableComponent`.

class Table::TableComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
