# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Footer::FooterComponent`.
# Please instead update this file by running `bin/tapioca dsl Footer::FooterComponent`.

class Footer::FooterComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
