# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Skeleton::ImageComponent`.
# Please instead update this file by running `bin/tapioca dsl Skeleton::ImageComponent`.

class Skeleton::ImageComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
