# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Skeleton::TextComponent`.
# Please instead update this file by running `bin/tapioca dsl Skeleton::TextComponent`.

class Skeleton::TextComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
