# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RichText::TrixComponent`.
# Please instead update this file by running `bin/tapioca dsl RichText::TrixComponent`.

class RichText::TrixComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
