# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tab::ContentsComponent`.
# Please instead update this file by running `bin/tapioca dsl Tab::ContentsComponent`.

class Tab::ContentsComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
