# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tab::ContentComponent`.
# Please instead update this file by running `bin/tapioca dsl Tab::ContentComponent`.

class Tab::ContentComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
