# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tab::HeaderComponent`.
# Please instead update this file by running `bin/tapioca dsl Tab::HeaderComponent`.

class Tab::HeaderComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
