# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tab::TabComponent`.
# Please instead update this file by running `bin/tapioca dsl Tab::TabComponent`.

class Tab::TabComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
