# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Navbar::NavbarComponent`.
# Please instead update this file by running `bin/tapioca dsl Navbar::NavbarComponent`.

class Navbar::NavbarComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
