# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Stepper::StepperComponent`.
# Please instead update this file by running `bin/tapioca dsl Stepper::StepperComponent`.

class Stepper::StepperComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
