# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Accordion::AccordionComponent`.
# Please instead update this file by running `bin/tapioca dsl Accordion::AccordionComponent`.

class Accordion::AccordionComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
