# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Accordion::BodyComponent`.
# Please instead update this file by running `bin/tapioca dsl Accordion::BodyComponent`.

class Accordion::BodyComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
