# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Accordion::HeaderComponent`.
# Please instead update this file by running `bin/tapioca dsl Accordion::HeaderComponent`.

class Accordion::HeaderComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
