# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Modal::ModalComponent`.
# Please instead update this file by running `bin/tapioca dsl Modal::ModalComponent`.

class Modal::ModalComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
