# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Indicator::DotComponent`.
# Please instead update this file by running `bin/tapioca dsl Indicator::DotComponent`.

class Indicator::DotComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
