# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Indicator::IndicatorComponent`.
# Please instead update this file by running `bin/tapioca dsl Indicator::IndicatorComponent`.

class Indicator::IndicatorComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
