# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Indicator::SpinnerComponent`.
# Please instead update this file by running `bin/tapioca dsl Indicator::SpinnerComponent`.

class Indicator::SpinnerComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
