# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Form::SearchComponent`.
# Please instead update this file by running `bin/tapioca dsl Form::SearchComponent`.

class Form::SearchComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
