# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Symbol::DotComponent`.
# Please instead update this file by running `bin/tapioca dsl Symbol::DotComponent`.

class Symbol::DotComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
