# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Drawer::LeftComponent`.
# Please instead update this file by running `bin/tapioca dsl Drawer::LeftComponent`.

class Drawer::LeftComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
