# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `HorizontalLine::IconComponent`.
# Please instead update this file by running `bin/tapioca dsl HorizontalLine::IconComponent`.

class HorizontalLine::IconComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
