# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `HorizontalLine::ShapeComponent`.
# Please instead update this file by running `bin/tapioca dsl HorizontalLine::ShapeComponent`.

class HorizontalLine::ShapeComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
