# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `HorizontalLine::TextComponent`.
# Please instead update this file by running `bin/tapioca dsl HorizontalLine::TextComponent`.

class HorizontalLine::TextComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
