# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `HorizontalLine::TrimComponent`.
# Please instead update this file by running `bin/tapioca dsl HorizontalLine::TrimComponent`.

class HorizontalLine::TrimComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
